[2018-06-15 15:28:39 +0800] [19410] [INFO] Goin' Fast @ http://127.0.0.1:7000
[2018-06-15 15:28:39 +0800] [19410] [INFO] Starting worker [19410]
[2018-06-15 15:31:12 +0800] - (sanic.access)[INFO][1:2]: POST http://localhost:7000/upimg  200 71
[2018-06-15 15:33:06 +0800] [19627] [INFO] Goin' Fast @ http://127.0.0.1:7000
[2018-06-15 15:33:06 +0800] [19627] [ERROR] Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1083, in uvloop.loop.Loop._create_server
  File "uvloop/handles/streamserver.pyx", line 51, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 89, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 48] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 591, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1422, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1599, in create_server
  File "uvloop/loop.pyx", line 1087, in uvloop.loop.Loop._create_server
OSError: [Errno 48] error while attempting to bind on address ('127.0.0.1', 7000): address already in use
[2018-06-15 15:33:06 +0800] [19627] [INFO] Server Stopped
[2018-06-15 15:44:25 +0800] [20002] [INFO] Goin' Fast @ http://127.0.0.1:7000
[2018-06-15 15:44:25 +0800] [20002] [ERROR] Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1083, in uvloop.loop.Loop._create_server
  File "uvloop/handles/streamserver.pyx", line 51, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 89, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 48] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 591, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1422, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1599, in create_server
  File "uvloop/loop.pyx", line 1087, in uvloop.loop.Loop._create_server
OSError: [Errno 48] error while attempting to bind on address ('127.0.0.1', 7000): address already in use
[2018-06-15 15:44:25 +0800] [20002] [INFO] Server Stopped
[2018-06-15 15:46:30 +0800] - (sanic.access)[INFO][1:2]: POST http://localhost:7000/upimg  200 71
[2018-06-15 15:50:13 +0800] [20902] [INFO] Goin' Fast @ http://127.0.0.1:7000
[2018-06-15 15:50:13 +0800] [20902] [INFO] Starting worker [20902]
[2018-06-15 16:02:47 +0800] [21233] [INFO] Goin' Fast @ http://127.0.0.1:7000
[2018-06-15 16:02:47 +0800] [21233] [INFO] Starting worker [21233]
[2018-06-15 16:02:54 +0800] - (sanic.access)[INFO][1:2]: POST http://127.0.0.1:7000/upimg  200 71
[2018-06-15 16:02:59 +0800] [21233] [INFO] KeepAlive Timeout. Closing connection.
[2018-06-15 16:04:24 +0800] - (sanic.access)[INFO][1:2]: POST http://127.0.0.1:7000/upimg  200 71
[2018-06-15 16:04:29 +0800] [21233] [INFO] KeepAlive Timeout. Closing connection.
[2018-06-15 16:11:54 +0800] [21942] [INFO] Goin' Fast @ http://127.0.0.1:7000
[2018-06-15 16:11:54 +0800] [21942] [INFO] Starting worker [21942]
[2018-06-15 16:12:04 +0800] - (sanic.access)[INFO][1:2]: POST http://127.0.0.1:7000/upimg  200 71
[2018-06-15 16:12:09 +0800] [21942] [INFO] KeepAlive Timeout. Closing connection.
